# fly.toml app configuration file generated for nba-agis-metric-d9sfxq on 2025-05-30T13:39:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nba-agis-metric-d9sfxq'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
