app = "dynastat"
primary_region = "ewr" # Change this to your preferred region
kill_signal = "SIGINT"
kill_timeout = 5

# Remove the buildpacks builder since we're using Dockerfile
# [build]
#   builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 